name: CI

on:
  release:
    types:
      - created

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get bibliography
        run: python zotero-bib-to-gh.py
        env:
          ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
          ZOTERO_BEARER_TOKEN: ${{ secrets.ZOTERO_BEARER_TOKEN }}

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.0.0
        with:
          filename: thesis.tex
          options: -lualatex

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: thesis.pdf
        env:
          GITHUB_TOKEN: ${{ github.token }}